### ISSUE TITLE
Support `provider: github`

### ISSUE THREAD

**Issue by wilsonehusin** [bindl-dev/bindl#17]
Currently, [programs need to specify complete URL template](https://github.com/xargs-dev/bindl/blob/245c7d0451d68e471d1f73d59c76a2b8215b2db2/bindl.yaml#L13).

This is helpful to support all sources. However, most programs come from GitHub releases. Would be nice to have something simplified and auto-detect the common pattern (or [lookup from GitHub API](https://docs.github.com/en/rest/reference/releases#get-a-release-by-tag-name)), such that the config manifest can look simpler like:

```yaml
name: myprogram
version: 0.1.0
provider: github
path: myorg/myprogram
overlay:
  Host: https://mygithubenterprise.com  # optional, defaults to "https://github.com"
```

While the lockfile manifest should remain the same.

(Or at least I don't think there is a need to change it)
