### ISSUE TITLE
Support matrix result override

### ISSUE THREAD

**Issue by wilsonehusin** [bindl-dev/bindl#77]
While we currently support individual overlay of `OS` and `Arch`, such change applies across all matrix result. I think there might be value in allowing overrides for matrix result too. Consider this scenario:

```
myprogram-Darwin-amd64.zip
myprogram-Linux-amd64-static.zip
```

I'm thinking it might look like this:

```yaml
overlay:
  OS:
    linux: Linux
    darwin: Darwin
overrides:
  - OS: linux
    Arch: amd64
    Value: 'myprogram-Linux-amd64-static.zip'
```

Not ideal that we have to do this, but I can understand scenarios of `CGO` compilation and why maintainers choose this route.
